# Generated by Django 3.0.5 on 2021-04-14 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_for', models.DateTimeField()),
                ('sleep_start', models.CharField(max_length=200)),
                ('sleep_end', models.CharField(max_length=200)),
                ('exercise', jsonfield.fields.JSONField()),
                ('nutrition', jsonfield.fields.JSONField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
